name: Test Webhook

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Echo mensaje
        run: echo "Probando webhook de GitHub Actions"
